# kernel-core package version to be installed in the $(uname -r) format
KERNEL_UNAME=5.14.0-570.12.1.el9_6.x86_64
# NVIDIA Driver Version
NVIDIA_DRIVER_VERSION=550.144.03
# kata-containers rpm filename to be installed. It must be relative to the current directory
KATA_RPM_FILENAME=kata-containers-3.15.0-1.rhaos4.19.el9.x86_64.rpm
# Organization ID for the Red Hat Subscription
ORG_ID=<org_id>
# Activation Key for the Red Hat Subscription
ACTIVATION_KEY=<activation-key-name>
# Any extra arguments taken by setup.sh
VERBOSE=1
