
# RHEL 10 podvm-payload
FROM quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload:osc-podvm-payload-on-pull-request-wddt2-build-image-index AS rhel10-podvm-payload

####################################
# STAGE 1: Setup the initrds builder
####################################

FROM localhost/rhel10-nvidia-drivers:1.0 AS initrds-builder-setup

ARG KERNEL_UNAME
ARG KATA_RPM_FILENAME
ARG ORG_ID
ARG ACTIVATION_KEY

WORKDIR /root

COPY ${KATA_RPM_FILENAME} /root/

# EPEL is required for busybox and iptables-legacy
RUN subscription-manager register --org ${ORG_ID} --activationkey ${ACTIVATION_KEY} \
    && subscription-manager repos --enable codeready-builder-for-rhel-10-x86_64-rpms \
    && dnf config-manager --best --nodocs --setopt=install_weak_deps=False --save \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

# Install dependencies, including kata-containers
RUN KERNEL_VERSION=$(echo ${KERNEL_UNAME} | rev | cut -d. -f2- | rev) \
    && dnf install -y \
        xz jq policycoreutils dbus-daemon rsync chrony rsyslog \
        ${KATA_RPM_FILENAME} \
        iptables

# Copy pause bundle
# FIXME: repack it as rootfs.sh requires it to be compressed with xz
COPY --from=rhel10-podvm-payload /pause-bundle.tar.gz /root/
RUN mkdir -p /root/pause \
    && tar xf pause-bundle.tar.gz -C pause \
    && tar -cJvf pause-bundle.tar.xz -C pause .

# Copy and extract podvm-binaries.tar.gz
COPY --from=rhel10-podvm-payload /podvm-binaries.tar.gz /root/
RUN mkdir -p /root/podvm-binaries \
    && tar -xf /root/podvm-binaries.tar.gz -C /root/podvm-binaries/

# Copy kata-agent and rego policy
COPY agent /root/agent
RUN cd /root/agent/usr/libexec/kata-containers \
    && mkdir -p agent/usr/bin kata-opa \
    && cp -fv /root/podvm-binaries/usr/local/bin/kata-agent agent/usr/bin/ \
    && cp -fv /root/podvm-binaries/etc/kata-opa/allow-all.rego kata-opa/

# Create coco-guest-components tarball
RUN mkdir -p /root/coco-guest-components/{usr/local/bin,etc} \
    && cd /root/coco-guest-components \
    && cp -fv /root/podvm-binaries/usr/local/bin/{api-server-rest,attestation-agent,confidential-data-hub,luks-encrypt-storage} usr/local/bin/ \
    && cp -fv /root/podvm-binaries/etc/ocicrypt_config.json etc/ \
    && tar -cJvf ../coco-guest-components.tar.xz .

# Install files from local filesystem.
# FIXME: push these files/changes to the kata-containers.rpm
RUN mkdir -p /usr/libexec/kata-containers/osbuilder/{systemd,systemd/system,dracut,dracut/dracut.conf.d}
COPY osbuilder/kata-osbuilder.sh /usr/libexec/kata-containers/osbuilder/
COPY osbuilder/systemd/* /usr/libexec/kata-containers/osbuilder/systemd/
COPY osbuilder/dracut/dracut-kata*.conf /usr/libexec/kata-containers/osbuilder/dracut/
COPY osbuilder/dracut/dracut.conf.d/15-dracut.conf /usr/libexec/kata-containers/osbuilder/dracut/dracut.conf.d/

# Workaround: sudo
# initrd-builder.sh requires sudo, but enabling it container adds some unnecessary complexity
RUN printf '#!/bin/bash \n $@' > /bin/sudo \
    && chmod +x /bin/sudo

# Clean up
RUN subscription-manager unregister \
    && dnf clean all \
    && rm /root/${KATA_RPM_FILENAME}

#############################
# Stage 2: Build the initrds
#############################

FROM initrds-builder-setup AS initrds-builder

ARG KERNEL_UNAME

# kata-snp initrd
RUN DEBUG=1 /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k "${KERNEL_UNAME}" -t "kata-snp" -a "/root/agent" -u
# kata-nvidia-gpu initrd
RUN DEBUG=1 /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k "${KERNEL_UNAME}" -t "kata-nvidia-gpu" -a "/root/agent"
# kata-nvidia-gpu-snp initrd
RUN DEBUG=1 /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k "${KERNEL_UNAME}" -t "kata-nvidia-gpu-snp" -a "/root/agent"

# Remove sudo workaround
RUN rm -f /bin/sudo

# Create kata-initrds tarball
RUN mkdir -p /root/initrds \
    && cd /root/initrds \
    && rm -rf * \
    && mkdir -p usr/share/kata-containers/ \
    && cp -avP /usr/share/kata-containers/osbuilder-images usr/share/kata-containers/ \
    && tar -czvf /kata-initrds.tar.gz .

# Create configs tarball
COPY configs /root/configs
RUN cd /root/configs/etc/kata-containers \
    && mkdir -p \
        kata-snp/config.d \
        kata-tdx/config.d \
        kata-nvidia-gpu/config.d \
        kata-nvidia-gpu-snp/config.d \
        kata-nvidia-gpu-tdx/config.d \
    && tar -czvf /kata-configs.tar.gz -C /root/configs .

###################################
# Stage 3: Compose the final image
###################################

FROM registry.access.redhat.com/ubi10/ubi:latest AS rhel10-kata-initrds

COPY --from=initrds-builder /kata-initrds.tar.gz /
COPY --from=initrds-builder /kata-configs.tar.gz /
RUN if [ -e /host ]; then \cp /kata-initrds.tar.gz /kata-configs.tar.gz /host/; fi