#!/bin/bash

set -o errexit
set -o pipefail
set -o errtrace

trap exit_handler EXIT

readonly SCRIPTNAME=$(basename "$0")
readonly NV_DRIVER_VERSION="550.144.03"

#KERNEL_UNAME=${KERNEL_UNAME:-"5.14.0-570.12.1.el9_6.x86_64"}

parse_args()
{
    while getopts "a:dhik:o:p:r:u:" opt
    do
        case $opt in
            a) AGENT_DIR_PREFIX="${OPTARG}" ;;
            d) set -o xtrace ;;
            h) usage 0 ;;
            i) GENERATE_IMAGE=1 ;;
            k) KERNEL_UNAME="${OPTARG}" ;;
            o) OSBUILDER_DIR="${OPTARG}" ;;
            p) ACTIVATION_KEY="${OPTARG}" ;;
            r) KATA_RPM_PATH="${OPTARG}" ;;
            u) ORG_ID="${OPTARG}" ;;
            *) usage 1 ;;
        esac
    done
    shift $(($OPTIND - 1))

    if [ -n "$*" ]; then
        die "Unhandled options: '$*'"
    fi

    if [ -z "${KERNEL_UNAME}" ] \
       || [ -z "${KATA_RPM_PATH}" ] \
       || [ -z "${ORG_ID}" ] \
       || [ -z "${ACTIVATION_KEY}" ] \
       ; then
        die "Mandatory parameters: -k -p -r -u"
    fi
}

usage()
{
    cat <<EOT

Usage: ${SCRIPTNAME} [options]

This script builds the kata appliance initrd and image and adds
stable symlink paths in ${IMAGE_TOPDIR}

This script is called at kata-osbuilder at RPM install %post time and
via kata-osbuilder-generate.service

Options:
  -a DIRNAME    Use the passed directory as the prefix of the agent_dir
                (i.e. usr/libexec/kata-containers/agent/).  It's
                mostly useful for pointing to an uninstalled kata-agent.
	            Default: ${AGENT_DIR_PREFIX}

  -d            Enable debug.

  -h            Show this help message

  -i            Also generate media for kata image= option. kata
                image= doesn't work out of the box with Fedora/RHEL
                distro kernels so media is not generated by default.

  -k VERSION    [Required] Kernel version to use. Must be in 'uname -r' format.

  -o DIRNAME    Use the passed directory for osbuilder code. Point
                To a git checkout if you want to use upstream osbuilder.
                Default: ${OSBUILDER_DIR}

  -p KEY        Activation key of the Red Hat subscription

  -r PATH       [Required] kata-containers rpm to be installed.

  -u ORG_ID     Organization ID of the Red Hat subscription

EOT

    exit $1
}

exit_handler()
{
    subscription-manager unregister &> /dev/null
}

die()
{
    error "$*"
    exit 1
}

error()
{
    echo "ERROR: ${SCRIPTNAME}: $*" >&2
}


info()
{
    echo "${SCRIPTNAME}: $*"
}

build_drivers()
{
    # Download NVIDIA run file
    curl -LO https://us.download.nvidia.com/tesla/${NV_DRIVER_VERSION}/NVIDIA-Linux-x86_64-${NV_DRIVER_VERSION}.run
    chmod +x ./NVIDIA-Linux-x86_64-${NV_DRIVER_VERSION}.run

    ./NVIDIA-Linux-x86_64-${NV_DRIVER_VERSION}.run \
        -m=kernel-open \
        --no-rebuild-initramfs \
        --no-dkms \
        --no-systemd \
        --skip-module-load \
        --no-install-compat32-libs \
        --ui=none \
        --no-questions \
        --expert \
        --x-library-path=/usr/lib64 \
        --module-signing-secret-key=/root/private_key.priv \
        --module-signing-public-key=/root/public_key.pem \
        --kernel-name=${KERNEL_UNAME}
}

# Install build dependencies
build_prepare()
{
    local DRIVER_STREAM=$(echo ${NV_DRIVER_VERSION} | cut -d '.' -f 1)
    local KERNEL_VERSION=$(echo ${KERNEL_UNAME} | rev | cut -d. -f2- | rev)

    # Enable codeready
    subscription-manager register --org ${ORG_ID} --activationkey ${ACTIVATION_KEY}
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms

    # Install EPEL RHEL9 for busybox
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

    # Install cuda repo for rhel9
    dnf config-manager --add-repo=https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
    dnf config-manager --best --nodocs --setopt=install_weak_deps=False --save

    dnf -y module enable nvidia-driver:${DRIVER_STREAM}-open/default

    dnf install -y \
        sudo syslog busybox \
        ${KATA_RPM_PATH} \
        {kernel-core,kernel-devel}-${KERNEL_VERSION} \
        vulkan-loader \
        nvidia-container-toolkit

    # Generate signing key
    openssl req -new -nodes -utf8 -sha256 -days 36500 -batch -x509 \
        -config default_x509.genkey -outform PEM \
        -out /root/public_key.pem -keyout /root/private_key.priv

        # nvidia-driver-NVML-${DRIVER_VERSION} \
        # nvidia-driver-cuda-libs-${DRIVER_VERSION} \

#    KVER=$(rpm -q --qf "%{VERSION}" kernel-core)
#    KREL=$(rpm -q --qf "%{RELEASE}" kernel-core | sed 's/\.el.\(_.\)*$//')
#    KDIST=$(rpm -q --qf "%{RELEASE}" kernel-core | awk -F '.' '{ print "."$NF}')
}

generate_initrd()
{
    mkdir -p /var/cache/kata-containers && \
    /usr/libexec/kata-containers/osbuilder/kata-osbuilder.sh -k ${KERNEL_UNAME} -u
}

save_artifacts()
{
    # Artifacts:
    # initrds and its symlinks
    # kernel symlink
    
    echo "Creating /host/kata-artifacts.tar.gz"
    
}

main()
{
    parse_args $*
    build_prepare
    build_drivers
    generate_initrd
    #save_artifacts
    info "Done"
}

main $*
