#!/usr/bin/bash

set -o errexit
set -o nounset
set -o pipefail

DEBUG=${DEBUG:-}

[ -n "${DEBUG}" ] && set -o xtrace

trap exit_handler EXIT

readonly SCRIPTNAME="$0"
readonly DISTRO=`grep '^ID=' /etc/os-release | awk '{print $2}' FS='=' |\
 sed 's/[[:space:]]*"//g; s/"[[:space:]]*//g; s/ //g'`
readonly IMAGE_TOPDIR="${IMAGE_TOPDIR:-"/usr/share/kata-containers/osbuilder-images"}"
DRACUT_ROOTFS=""
TEMP_BUILD_DIR=""
# rpm %check sets this to run the script without overwriting host
# content, and not requiring root
readonly TEST_MODE="${TEST_MODE:-}"

ARG_KVERSION=`uname -r`
ARG_OSBUILDER_DIR="/usr/libexec/kata-containers/osbuilder"
ARG_AGENT_DIR_PREFIX="/usr/libexec/kata-containers/agent"
ARG_EXIT_IF_GENERATED=""
ARG_DELETE_EXISTING_IMAGES=""
ARG_KEEP_BUILD_DIR=""
ARG_RUNTIME_CLASS="kata"
ARG_GENERATE_IMAGE=""
ARG_PAUSE_IMAGE_TARBALL="/root/pause-bundle.tar.xz"
ARG_GUEST_COMPONENTS_TARBALL="/root/coco-guest-components.tar.xz"

# Supported runtime classes
readonly RUNTIME_CLASSES=( \
  "kata" \
  "kata-snp" \
  "kata-nvidia-gpu" \
  "kata-nvidia-gpu-snp" \
)

# ANSI colors used for printing messages
readonly ANSI_RED_COLOR="\e[31m"
readonly ANSI_GREEN_COLOR="\e[32m"
readonly ANSI_MAGENTA_COLOR="\e[35m"
readonly ANSI_COLOR_RESET="\e[0m"

die()
{
    error "$*"
    exit 1
}

error()
{
    echo -e "${ANSI_RED_COLOR}BUILDER_ERROR: $*${ANSI_COLOR_RESET}" >&2
}

new_level()
{
    echo -e "${ANSI_MAGENTA_COLOR}***** $* *****${ANSI_COLOR_RESET}" >&2
}

info()
{
    echo -e "${ANSI_GREEN_COLOR}BUILDER_INFO: $*${ANSI_COLOR_RESET}" >&2
}

delete_build_directory()
{
    if [ -n "${TEMP_BUILD_DIR}" ] && [ -d "${TEMP_BUILD_DIR}" ]; then
        rm -rf ${TEMP_BUILD_DIR};
        info "${TEMP_BUILD_DIR} deleted"
    fi
}

exit_handler()
{
    [ -z "${ARG_KEEP_BUILD_DIR}" ] && delete_build_directory
}

usage()
{
    cat <<EOT

Usage: ${SCRIPTNAME} [options]

This script builds the kata appliance initrd and image and adds
stable symlink paths in ${IMAGE_TOPDIR}

This script is called at kata-osbuilder at RPM install %post time

Options:
  -a DIRNAME    Use the passed directory as the agent_dir prefix. It's
                mostly useful for pointing to an uninstalled kata-agent.
                Default: "${ARG_AGENT_DIR_PREFIX}"

  -c            Check if an initrd is already generated for the current
                kernel, and if so, simply exit

  -e PATH       Pause bundle tarball compressed with xz.
                Default: ${ARG_PAUSE_IMAGE_TARBALL}

  -g PATH       Coco guest components tarball compressed with xz.
                Default: ${ARG_GUEST_COMPONENTS_TARBALL}

  -h            Show this help message

  -i            Also generate media for kata image= option. kata
                image= doesn't work out of the box with Fedora/RHEL
                distro kernels so media is not generated by default.

  -k UNAME_R    Manually specify kernel version to use. Default comes
                from uname. Default: ${ARG_KVERSION}

  -o DIRNAME    Use the passed directory for osbuilder code. Point
                To a git checkout if you want to use upstream osbuilder.
                Default: ${ARG_OSBUILDER_DIR}

  -p PATH       Agent policy
                Default: ${ARG_AGENT_POLICY}

  -s            Don't remove build directory: /tmp/osbuilder-XXXXXX

  -t RCLASS     Generate initrd for the RCLASS runtime class.
                Default: "kata".

  -u            Delete existing osbuilder images: ${IMAGE_TOPDIR}

EOT

    exit $1
}

parse_args()
{
    while getopts "a:ce:g:hik:o:p:st:u" opt
    do
        case $opt in
            a) ARG_AGENT_DIR_PREFIX="${OPTARG}" ;;
            c) ARG_EXIT_IF_GENERATED=1 ;;
            e) ARG_PAUSE_IMAGE_TARBALL="${OPTARG}" ;;
            g) ARG_GUEST_COMPONENTS_TARBALL="${OPTARG}" ;;
            h) usage 0 ;;
            i) ARG_GENERATE_IMAGE=1 ;;
            k) ARG_KVERSION="${OPTARG}" ;;
            o) ARG_OSBUILDER_DIR="${OPTARG}" ;;
            p) ARG_AGENT_POLICY="${OPTARG}" ;;
            s) ARG_KEEP_BUILD_DIR=1 ;;
            t) ARG_RUNTIME_CLASS="${OPTARG}" ;;
            u) ARG_DELETE_EXISTING_IMAGES=1 ;;
            *) usage 1 ;;
        esac
    done
    shift $(($OPTIND - 1))

    if [ -n "$*" ]; then
        error "Unhandled options: '$*'"
        usage 1
    fi

    validate_runtime_class
}

# Die if a runtime class is not supported
validate_runtime_class() {
    for rt in ${RUNTIME_CLASSES[@]};
    do
        [ "${rt}" == "${ARG_RUNTIME_CLASS}" ] && return 0;
    done
    die "Runtime class ${ARG_RUNTIME_CLASS} not supported"
}

exit_if_osbuilder_images_already_generated()
{
    local initrd_symlink="${IMAGE_TOPDIR}/${ARG_RUNTIME_CLASS}.initrd"
    local image_symlink="${IMAGE_TOPDIR}/${ARG_RUNTIME_CLASS}.image"

    [ -z "${ARG_EXIT_IF_GENERATED}" ] && return 0;

    # Check if the symlinks exist and they are not broken
    if [ ! -e ${initrd_symlink} ]; then
        return 0
    fi
    if [ -n "${GENERATE_IMAGE}" ] && [ ! -e ${image_symlink} ]; then
        return 0
    fi

    info "Nothing to generate. Exiting."
    exit 0
}

delete_existing_osbuilder_images()
{
    local osbuilder_images_dir="${IMAGE_TOPDIR}"

    [ -z "${IMAGE_TOPDIR}" ] || [ "$(basename ${IMAGE_TOPDIR})" != "osbuilder-images" ] && \
        die "${FUNCNAME}: invalid ${IMAGE_TOPDIR}"

    info "Delete ${osbuilder_images_dir}"
    rm -rf ${osbuilder_images_dir}/*
}

copy_the_host_kernel()
{
    local prefix="$1"
    local kernel_host_modules_dir="/lib/modules/${ARG_KVERSION}"

    [ ! -d "$kernel_host_modules_dir" ] && die "$FUNCNAME: ${kernel_host_modules_dir} directory not found"
    [ ! -d "$prefix" ] && die "$FUNCNAME: invalid prefix argument"

    prefix="${prefix}/dest"
    local kernel_guest_target="${ARG_KVERSION}/vmlinuz.container"

    local kernel_host_path=""
    for vmlinux in vmlinuz vmlinux; do
        kernel_host_path="${kernel_host_modules_dir}/${vmlinux}"
        if [ -e "${kernel_host_path}" ] ; then
            local kernel_guest_path="${prefix}/${kernel_guest_target}"
            
            # Copy the host kernel to the guest to prevent the guest from breaking
            # if the host kernel is updated. Ultimately, the guest kernel and initrd are
            # pre-generated and installed in the node.
            info "Copy host kernel to ${kernel_guest_path}"
            mkdir -p "$(dirname ${kernel_guest_path})"
            \cp -avf "${kernel_host_path}" "${kernel_guest_path}"

            ln -snf "${kernel_guest_target}" "${prefix}/${ARG_RUNTIME_CLASS}.kernel"
            return 0
        fi
    done

    die "$FUNCNAME: vmlinu* not found in ${kernel_host_modules_dir}"
}

tweak_dracut_rootfs()
{
    info "Applying common tweaks to dracut rootfs"

    # Using the busybox dracut module sets /sbin/init -> busybox
    # We don't want that. Reset it to systemd
    ln -sf ../lib/systemd/systemd ${DRACUT_ROOTFS}/usr/sbin/init

    # override the auto-cpu-onlining udev rule
    # Workarounds KATA-747
    echo 'SUBSYSTEM=="cpu", ACTION=="add", TEST=="online", ATTR{online}=="0", ATTR{online}="0"' > ${DRACUT_ROOTFS}/usr/lib/udev/rules.d/99-rm-cpu-onlining.rules

    info "Copying agent directory tree into place"
    cp -ar ${ARG_AGENT_DIR_PREFIX}/usr/libexec/kata-containers/agent/* ${DRACUT_ROOTFS}

    # dracut doesn't have a native module for chrony
    # Fixes KATA-4007
    info "Copy chrony files"
    rsync -a /usr/sbin/chronyd ${DRACUT_ROOTFS}/usr/sbin/
    ldd /usr/sbin/chronyd | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
    rsync -a /etc/sysconfig/chronyd ${DRACUT_ROOTFS}/etc/sysconfig/
    rsync -a /usr/lib/systemd/system/chronyd.service ${DRACUT_ROOTFS}/usr/lib/systemd/system/
    echo "WantedBy=kata-containers.target" >> ${DRACUT_ROOTFS}/usr/lib/systemd/system/chronyd.service
    echo "chrony:x:992:" >> ${DRACUT_ROOTFS}/etc/group
    echo "chrony:x:994:992:chrony:/:/usr/sbin/nologin" >> ${DRACUT_ROOTFS}/etc/passwd
}

install_trusted_ca_bundle_to_rootfs() {
    if [ -n "${DRACUT_ROOTFS}" ]; then
        local extracted_dir="${DRACUT_ROOTFS}/etc/pki/ca-trust/extracted"

        info "Install trusted tls-ca-bundle.pem"

        mkdir -p "${extracted_dir}"
        update-ca-trust extract -o "${extracted_dir}"

        for cert_dir in "${DRACUT_ROOTFS}/etc/ssl" "${DRACUT_ROOTFS}/etc/pki/tls"; do
            mkdir -p ${cert_dir}
            ln -snf "${extracted_dir}/pem/tls-ca-bundle.pem" "${cert_dir}/cert.pem"
        done
    fi
}

# Write the modules-load file from all driver .ko.* files in the initrd
# Systemd will force this modules to be loaded at early boot
generate_modules_load_conf()
{
    local loadfile="${DRACUT_ROOTFS}/etc/modules-load.d/kata-modules.conf"
    local modpath

    info "Generate /etc/modules-load.d/kata-modules.conf"

    mkdir -p $(dirname $loadfile)

    for modpath in `find ${DRACUT_ROOTFS} -path \*lib/modules/\*\.ko\*`; do
        local name=$(echo $(basename ${modpath}) | cut -d '.' -f 1)
        if [ "${name}" != "ring_buffer_benchmark" ]; then
            echo "${name}" >> $loadfile
        fi
    done
}

run_kata_rootfs_builder()
{
    local agent_source_bin="${ARG_AGENT_DIR_PREFIX}/usr/libexec/kata-containers/agent/usr/bin/kata-agent"
    local agent_policy_file="${ARG_AGENT_DIR_PREFIX}/usr/libexec/kata-containers/kata-opa/allow-all.rego"
    local osbuilder_version="${DISTRO}-osbuilder-version-unknown"

    info "Calling osbuilder rootfs.sh on extracted rootfs"

    # Make kata specific adjustments
    case ${ARG_RUNTIME_CLASS} in
        "kata")
            AGENT_SOURCE_BIN="${agent_source_bin}" \
                ${ARG_OSBUILDER_DIR}/rootfs-builder/rootfs.sh \
                -o ${osbuilder_version} \
                -r ${DRACUT_ROOTFS}

            generate_modules_load_conf
            ;;

        "kata-snp" )
            AGENT_SOURCE_BIN="${agent_source_bin}" \
            AGENT_POLICY="yes" \
            AGENT_POLICY_FILE="${agent_policy_file}" \
            COCO_GUEST_COMPONENTS_TARBALL="${ARG_GUEST_COMPONENTS_TARBALL}" \
            PAUSE_IMAGE_TARBALL="${ARG_PAUSE_IMAGE_TARBALL}" \
            CONFIDENTIAL_GUEST="yes" \
                ${ARG_OSBUILDER_DIR}/rootfs-builder/rootfs.sh \
                -o ${osbuilder_version} \
                -r ${DRACUT_ROOTFS}

            # Copy dynamic libraries
            ldd ${DRACUT_ROOTFS}/usr/local/bin/api-server-rest | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/local/bin/attestation-agent | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/local/bin/confidential-data-hub | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/bin/kata-agent | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/

            info "Copy the systemd-remount-fs.service"
            cp /usr/lib/systemd/system/systemd-remount-fs.service ${DRACUT_ROOTFS}/usr/lib/systemd/system/
            cp /usr/lib/systemd/systemd-remount-fs ${DRACUT_ROOTFS}/usr/lib/systemd/

            install_trusted_ca_bundle_to_rootfs

            generate_modules_load_conf
            ;;

        "kata-nvidia-gpu" | "kata-nvidia-gpu-snp" )
            # systemd-nvidia-cdi
            cp ${ARG_OSBUILDER_DIR}/systemd/nvidia-cdi.service ${DRACUT_ROOTFS}/usr/lib/systemd/system/
            cp ${ARG_OSBUILDER_DIR}/systemd/systemd-nvidia-cdi.sh ${DRACUT_ROOTFS}/usr/lib/systemd/
            systemctl add-wants --root=${DRACUT_ROOTFS} multi-user.target nvidia-cdi.service

            if [ "${ARG_RUNTIME_CLASS}" == "kata-nvidia-gpu" ]; then
                # Comment out the command "nvida-smi conf-compute -srs 1" as this is not CoCo.
                sed -i '/^nvidia-smi conf-compute -srs 1/s/^/#&/' ${DRACUT_ROOTFS}/usr/lib/systemd/systemd-nvidia-cdi.sh

                AGENT_SOURCE_BIN="${agent_source_bin}" \
                AGENT_POLICY="yes" \
                AGENT_POLICY_FILE="${agent_policy_file}" \
                COCO_GUEST_COMPONENTS_TARBALL="${ARG_GUEST_COMPONENTS_TARBALL}" \
                PAUSE_IMAGE_TARBALL="${ARG_PAUSE_IMAGE_TARBALL}" \
                    ${ARG_OSBUILDER_DIR}/rootfs-builder/rootfs.sh \
                    -o ${osbuilder_version} \
                    -r ${DRACUT_ROOTFS}
            else
                AGENT_SOURCE_BIN="${agent_source_bin}" \
                AGENT_POLICY="yes" \
                AGENT_POLICY_FILE="${agent_policy_file}" \
                COCO_GUEST_COMPONENTS_TARBALL="${ARG_GUEST_COMPONENTS_TARBALL}" \
                PAUSE_IMAGE_TARBALL="${ARG_PAUSE_IMAGE_TARBALL}" \
                CONFIDENTIAL_GUEST="yes" \
                    ${ARG_OSBUILDER_DIR}/rootfs-builder/rootfs.sh \
                    -o ${osbuilder_version} \
                    -r ${DRACUT_ROOTFS}
            fi

            # Copy dynamic libraries
            ldd ${DRACUT_ROOTFS}/usr/local/bin/api-server-rest | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/local/bin/attestation-agent | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/local/bin/confidential-data-hub | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/
            ldd ${DRACUT_ROOTFS}/usr/bin/kata-agent | perl -lne 'print $1 if /=>\s+\/lib64\/(\S+)/o' | xargs -i rsync -aL /lib64/{} ${DRACUT_ROOTFS}/lib64/

            info "Copy the systemd-remount-fs.service"
            cp /usr/lib/systemd/system/systemd-remount-fs.service ${DRACUT_ROOTFS}/usr/lib/systemd/system/
            cp /usr/lib/systemd/systemd-remount-fs ${DRACUT_ROOTFS}/usr/lib/systemd/

            # blacklist nouveau
            mkdir -p ${DRACUT_ROOTFS}/etc/modprobe.d/
            echo "blacklist nouveau" > ${DRACUT_ROOTFS}/etc/modprobe.d/blacklist_nouveau.conf

            install_trusted_ca_bundle_to_rootfs

            generate_modules_load_conf

            # Don't use modprobe from busybox
            # Issue: "Invalid ELF header magic: != ELF"
            ;;

        *)
            die "$FUNCNAME: runtime class not supported \"${ARG_RUNTIME_CLASS}\""
            ;;
    esac

    # Mask initrd.target and default to multi-user.target
    # Temporary workaround for KATA-3944
    systemctl mask --root=${DRACUT_ROOTFS} initrd.target
    systemctl set-default --root=${DRACUT_ROOTFS} multi-user.target

}

generate_dracut_rootfs()
{
    [ ! -d "$1" ] || [ -z "${ARG_KVERSION}" ] && die "$FUNCNAME: invalid parameter"

    local prefix="$1"
    local dracut_arg_initrd="${prefix}/build/dracut-${ARG_RUNTIME_CLASS}.initrd"
    local dracut_arg_confdir="${ARG_OSBUILDER_DIR}/dracut/dracut.conf.d"
    local dracut_arg_conf="${ARG_OSBUILDER_DIR}/dracut/dracut-${ARG_RUNTIME_CLASS}.conf"
    local dracut_arg_verbose=""
    local dracut_arg_fips=""

    [ -n "${DRACUT_ROOTFS}" ] && [ -d "${DRACUT_ROOTFS}" ] && rm -rf ${DRACUT_ROOTFS}

    [ ! -f ${dracut_arg_conf} ] && dracut_arg_conf="/dev/null"

    [ -n "$DEBUG" ] && dracut_arg_verbose="-vvv"

    if [ -e "/proc/sys/crypto/fips_enabled" ] && [ "$(</proc/sys/crypto/fips_enabled)" -eq 1 ]; then
        dracut_arg_fips="-a fips "
    fi

    mkdir -p $(dirname "${dracut_arg_initrd}")

    # Generate initrd using dracut. Kata provides two drop-in dracut config files, so
    # let's use the same confdir for all initrds
    info "Dracut initrd: ${dracut_arg_initrd}"
    dracut ${dracut_arg_verbose}  \
        --confdir "${dracut_arg_confdir}" \
        --no-compress \
        --conf ${dracut_arg_conf} \
        ${dracut_arg_fips} ${dracut_arg_initrd} ${ARG_KVERSION}

    DRACUT_ROOTFS="${prefix}/build/dracut-${ARG_RUNTIME_CLASS}-rootfs"
    mkdir -p ${DRACUT_ROOTFS}

    # Extract initrd
    info "Extracting dracut initrd"
    cat ${dracut_arg_initrd} | \
        cpio --extract --preserve-modification-time --make-directories --directory=${DRACUT_ROOTFS}
}

generate_kata_initrd()
{
    [ ! -d "$1" ] && die "$FUNCNAME: invalid parameter"

    local prefix="$1"
    local suffix="${ARG_KVERSION}/${ARG_RUNTIME_CLASS}.initrd"
    local symlink="${prefix}/dest/${ARG_RUNTIME_CLASS}.initrd"
    local initrd="${prefix}/dest/${suffix}"

    mkdir -p $(dirname "${initrd}")

    info "kata initrd: ${suffix}"
    ${ARG_OSBUILDER_DIR}/initrd-builder/initrd_builder.sh -o "${initrd}" "${DRACUT_ROOTFS}"
    ln -sf "${suffix}" "${symlink}"
}

generate_kata_image()
{
    [ ! -d "$1" ] && die "$FUNCNAME: invalid paramter"

    local prefix="$1"
    local suffix="${ARG_KVERSION}/${ARG_RUNTIME_CLASS}.image"
    local symlink="${prefix}/dest/${ARG_RUNTIME_CLASS}.image"
    local image="${prefix}/dest/${suffix}"

    mkdir -p $(dirname "${image}")

    info "kata image: ${suffix}"
    NSDAX_BIN="${ARG_OSBUILDER_DIR}/nsdax" \
        ${ARG_OSBUILDER_DIR}/image-builder/image_builder.sh -o "${image}" "${DRACUT_ROOTFS}"
    ln -sf "${suffix}" "${symlink}"
}

generate_kata_rootfs()
{
        local prefix="$1"

        # To generate the rootfs, we build an initrd with dracut, extract
        # the initrd content, and then discard the initrd. We then rebuild
        # the initrd using the osbuilder native scripts.
        #
        # This is a bit wasteful, but it's the easiest way to work around
        # obuilder script inflexibility for now, which expect that some rootfs.sh
        # code is called on a fully populated distro root.

        generate_dracut_rootfs "$prefix"
        tweak_dracut_rootfs
        run_kata_rootfs_builder
}

install_generated_artifacts()
{
    local prefix="$1"

    [ ! -d "$1" ] && die "$FUNCNAME: invalid parameter"
    [ -n "${TEST_MODE}" ] && return 0

    info "Install artifacts to ${IMAGE_TOPDIR}"
    mkdir -p "${IMAGE_TOPDIR}" || die "Invalid ${IMAGE_TOPDIR}"
    \cp -avf ${TEMP_BUILD_DIR}/dest/* ${IMAGE_TOPDIR}/
}

main()
{
    parse_args $*

    [ -z "${TEST_MODE}" ] && [ "$(id -u)" -ne 0 ] && die "$0: must be run as root"

    if [ -n "${ARG_DELETE_EXISTING_IMAGES}" ]; then
        delete_existing_osbuilder_images
    else 
        [ -n "${ARG_EXIT_IF_GENERATED}" ] && exit_if_osbuilder_images_already_generated
    fi

    TEMP_BUILD_DIR=$(mktemp --directory -t osbuilder-XXXXXX)
    info "${TEMP_BUILD_DIR} created"

    new_level "${ARG_RUNTIME_CLASS}"

    copy_the_host_kernel "${TEMP_BUILD_DIR}"
    generate_kata_rootfs "${TEMP_BUILD_DIR}"
    generate_kata_initrd "${TEMP_BUILD_DIR}"
    [ -n "${ARG_GENERATE_IMAGE}" ] && generate_kata_image "${TEMP_BUILD_DIR}"

    install_generated_artifacts "${TEMP_BUILD_DIR}"
}

main $*
