# NVIDIA drivers
drivers+=" nvidia-drm nvidia-modeset nvidia-uvm nvidia "
drivers+=" efi_secret "
# overlay, storage etc.
drivers+=" overlay nfs dm-crypt dm-verity dm-mod libiscsi "

# Dependencies from kata nvidia_rootfs.sh:chisseled_compute()
# The libraries below requires building the NVIDIA runfile with --x-library-path=/usr/lib64
install_items+=" /usr/bin/nvidia-cdi-hook "
install_items+=" /usr/bin/nvidia-ctk "
install_items+=" /usr/bin/nvidia-persistenced "
install_items+=" /usr/bin/nvidia-smi "
install_items+=" /usr/lib64/libnvidia-ml.so "
install_items+=" /usr/lib64/libcuda.so "
install_items+=" /usr/lib64/libnvidia-cfg.so "

# Dependencies from kata nvidia_rootfs.sh:chisseled init()
install_items+=" /lib/firmware/nvidia "
# TODO: use the files below to check if the gpu device is supported by the driver
# install_items+=" /usr/share/nvidia/nvidia_driver_version "
# install_items+=" /usr/share/nvidia/nvidia_supported_gpu_devids "

# Dependencies from kata nvidia_rootfs.sh:chisseled_iptables()
install_items+=" /usr/sbin/iptables "
install_items+=" /usr/sbin/iptables-save "
install_items+=" /usr/sbin/iptables-restore "

# TODO: datacenter-gpu-manager (DCGM)
# TODO: nvidia-fabric-manager (NVSwitch)
